subAppClass: info.magnolia.ui.contentapp.browser.BrowserSubApp
class: info.magnolia.ui.contentapp.browser.BrowserSubAppDescriptor
contentConnector:
  includeProperties: false
  workspace: trains
  rootPath: /
  defaultOrder: jcrName
  nodeTypes:
    - icon: icon-node-data
      name: mgnl:train
actions:
  addTrain:
    subAppId: detail
    icon: icon-add-item
    nodeType: mgnl:train
    appName: trains-app
    class: info.magnolia.ui.contentapp.detail.action.CreateItemActionDefinition
    availability:
      writePermissionRequired: true
      root: true
      nodes: false
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
  editTrain:
    subAppId: detail
    icon: icon-edit
    appName: trains-app
    class: info.magnolia.ui.contentapp.detail.action.EditItemActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
      nodeTypes:
        mgnl-train: mgnl:train
  delete:
    command: markAsDeleted
    class: info.magnolia.ui.framework.action.MarkNodeAsDeletedActionDefinition
    availability:
      writePermissionRequired: true
  activate:
    command: activate
    icon: icon-publish
    catalog: versioned
    class: info.magnolia.ui.framework.action.ActivationActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
  deactivate:
    command: deactivate
    icon: icon-unpublish
    catalog: versioned
    class: info.magnolia.ui.framework.action.DeactivationActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
        - name: IsPublishedRule
          implementationClass: info.magnolia.ui.framework.availability.IsPublishedRule
  export:
    command: export
    icon: icon-export
    class: info.magnolia.ui.framework.action.ExportActionDefinition
    availability:
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
  import:
    icon: icon-import
    dialogName: ui-admincentral:import
    name: import
    class: info.magnolia.ui.framework.action.OpenCreateDialogActionDefinition
    availability:
      writePermissionRequired: true
      root: true
      nodes: false
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
  restorePreviousVersion:
    icon: icon-undo
    class: info.magnolia.ui.contentapp.detail.action.RestorePreviousVersionActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsDeletedRule
  activateDeleted:
    command: activate
    icon: icon-publish
    catalog: versioned
    class: info.magnolia.ui.framework.action.ActivationActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsDeletedRule
  confirmDeleteTrain:
    successActionName: delete
    icon: icon-delete
    class: info.magnolia.module.dependencies.action.DependencyAwareConfirmationActionDefinition
    availability:
      multiple: true
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule
  showVersions:
    icon: icon-show-versions
    class: info.magnolia.ui.contentapp.browser.action.ShowVersionsActionDefinition
    availability:
      root: false
      nodes: true
      rules:
        - name: HasVersionsRule
          implementationClass: info.magnolia.ui.framework.availability.HasVersionsRule
  restoreVersion:
    icon: icon-retrieve-versions
    class: info.magnolia.ui.contentapp.browser.action.RestoreVersionActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: HasVersionsRule
          implementationClass: info.magnolia.ui.framework.availability.HasVersionsRule
  duplicate:
    icon: icon-duplicate
    class: info.magnolia.ui.framework.action.DuplicateNodeActionDefinition
    availability:
      writePermissionRequired: true
      root: false
      nodes: true
      rules:
        - name: IsNotDeletedRule
          implementationClass: info.magnolia.ui.framework.availability.IsNotDeletedRule

actionbar:
  defaultAction: editTrain
  sections:
    - name: root
      groups:
        - name: addActions
          items:
            - name: addTrain
            - name: confirmDeleteTrain
        - name: editActions
          items:
            - name: editTrain
            - name: duplicate
        - name: activationActions
          items:
            - name: activate
            - name: deactivate
        - name: importExportActions
          items:
            - name: import
            - name: export
        - name: versionsActions
          items:
            - name: showVersions
            - name: restoreVersion
      availability:
        nodes: false
        root: true
    - name: train
      groups:
        - name: addActions
          items:
            - name: addTrain
            - name: confirmDeleteTrain
        - name: editActions
          items:
            - name: editTrain
            - name: duplicate
        - name: activationActions
          items:
            - name: activate
            - name: deactivate
        - name: importExportActions
          items:
            - name: import
            - name: export
        - name: versionsActions
          items:
            - name: showVersions
            - name: restoreVersion
      availability:
        nodeTypes:
          mgnl-train: mgnl:train
workbench:
  editable: false
  contentViews:
    - name: list
      class: info.magnolia.ui.workbench.list.ListPresenterDefinition
      columns: &columns
        - name: from
          label: trains-app.train.from.label
          sortable: true
          expandRatio: 2.0
          propertyName: from
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: to
          label: trains-app.train.to.label
          sortable: true
          expandRatio: 2.0
          propertyName: to
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: start
          label: trains-app.train.start.label
          sortable: true
          expandRatio: 1.0
          propertyName: start
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: end
          label: trains-app.train.end.label
          sortable: true
          expandRatio: 1.0
          propertyName: end
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: length
          label: trains-app.train.length.label
          sortable: true
          expandRatio: 1.0
          propertyName: length
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: numStops
          label: trains-app.train.numStops.label
          sortable: true
          expandRatio: 1.0
          propertyName: numStops
          class: info.magnolia.ui.workbench.column.definition.PropertyColumnDefinition
        - name: status
          width: 46
          displayInChooseDialog: false
          formatterClass: info.magnolia.ui.workbench.column.StatusColumnFormatter
          class: info.magnolia.ui.workbench.column.definition.StatusColumnDefinition
    - name: search
      class: info.magnolia.ui.workbench.search.SearchPresenterDefinition
      columns: *columns